source 'https://github.com/CocoaPods/Specs.git'

pod 'AVOSCloud'
pod 'AVOSCloudUI'
pod 'AVOSCloudSNS'
pod 'SinchRTC'
pod 'HexColors'
pod 'FontAwesomeKit'
pod 'JSQMessagesViewController'
pod 'JSQSystemSoundPlayer'
pod 'AHKActionSheet'
pod 'MBProgressHUD'
pod 'pop'
pod 'Stripe'
pod 'PaymentKit'